config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # letter opener config
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :pages do
    resource :check, only: [ :create ]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :last_result, class_name: "Result", optional: true
  has_many :results

  validates :name, presence: true
  validates :url, presence: true
  validates :check_type, presence: true
  validates :selector, presence: true
  validates :match_text, presence: { if: -> { check_type == "text" } }

  def run_and_notify
    run_check
    last_result.notify if last_result.success?
  end

  def run_check
    scrapper = Scrapper.new url
    result = case check_type
             when "text" then scrapper.text(selector: selector).downcase == match_text.downcase
             when "exists" then scrapper.present?(selector: selector)
             when "not_exists" then !scrapper.present?(selector: selector)
             end
    results.create(success: result)
    update(last_result: results.last)
  end
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :page

  def notify
    UserMailer.with(result: self).success.deliver_later
  end
end

app/models/scrapper.rb
require "net/http"

class Scrapper
  attr_reader :document
  def initialize(url)
    response = Net::HTTP.get(URI(url))
    @document = Nokogiri::HTML(response)
  end

  def text(selector:)
    document.at_css(selector).text
  end

  def present?(selector:)
    document.at_css(selector)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  before_action :set_page

  def create
    @page.run_check
    redirect_to @page
  end

  private

  def set_page
    @page = Page.find params[:page_id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[ show edit update destroy ]

  # GET /pages or /pages.json
  def index
    @pages = Page.includes(:last_result)
  end

  # GET /pages/1 or /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to page_url(@page), notice: "Page was successfully created." }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to page_url(@page), notice: "Page was successfully updated." }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy!

    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def page_params
      params.require(:page).permit(:url, :check_type, :selector, :match_text, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Web Scrapper" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="max-w-4xl container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, placeholder: "My website" %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.url_field :url, placeholder: "https://example.org/..." %>
  </div>

  <div>
    <%= form.label :check_type, style: "display: block" %>
    <%= form.select :check_type, [%w[Text text], %w[Exists exists], ["Not exists", "not_exists"]] %>
  </div>

  <div>
    <%= form.label :selector, style: "display: block" %>
    <%= form.text_field :selector, placeholder: ".class" %>
  </div>

  <div>
    <%= form.label :match_text, style: "display: block" %>
    <%= form.text_field :match_text, placeholder: "Text to match" %>
  </div>

  <div class="mt-4">
    <%= form.submit class: "border border-gray-200 rounded shadow px-2 py-1 hover:bg-gray-100" %>
  </div>
<% end %>

app/views/pages/_page.html.erb
 <%= link_to page, id: dom_id(page), class: "p-4 -mx-4 hover:bg-gray-100" do %>
    <div class="flex">
      <div class="w-2/3">
        <h5 class="font-bold"><%= page.name %></h5>
        <div class="text-sm text-gray-700"><%= page.url %></div>
      </div>
      <div class="-my-4 flex flex-col justify-center items-center pl-1 border-solid border-l-2 border-gray-400 w-1/3">
        <% if page.last_result %>
            <!-- <h4 class="font-medium text-gray-700 font-bold">Recent results</h4> -->
            <%= render page.last_result %>
        <% else %>
          <h4 class="font-medium text-gray-700 font-bold">Not monitored</h4>
        <% end %>
        </div>
    </div>
  <% end %>

app/views/pages/edit.html.erb
<% content_for :title, "Editing page" %>
<div class="flex items-center justify-between">
  <h1 class="text-2xl font-bold truncate">
    <%= link_to "‹", @page, class: "p-2 rounded hover:bg-gray-100" %>
    Edit page
  </h1>
  <div class="flex items-center gap-2">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
    </svg>
    <%= button_to "Destroy this page", @page, method: :delete, data: {turbo_confirm: "Are you sure?"}, class: "font-bold hover:text-gray-700" %>
  </div>
</div>
<%= render "form", page: @page %>

<br>

app/views/pages/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Pages" %>

<div class="flex justify-between">
  <h1 class="text-2xl font-bold">Pages</h1>
  <%= link_to "New page", new_page_path, class: "border border-gray-200 rounded shadow px-2 py-1 hover:bg-gray-100" %>
</div>

<div id="pages" class="flex flex-col divide-y divide-gray-200">
  <%= render @pages %>
</div>

app/views/pages/new.html.erb
<% content_for :title, "New page" %>

<h1 class="text-2xl font-bold truncate">
  <%= link_to "‹", @page, class: "p-2 rounded hover:bg-gray-100" %>
  Monitor a page
</h1>

<%= render "form", page: @page %>

<br>

app/views/pages/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="flex justify-between max-h-10">
  <h1 class="text-2xl font-bold truncate">
    <%= link_to "‹", root_path, class: "p-2 rounded hover:bg-gray-100" %>
    <%= @page.name %>
  </h1>
    <div class="flex gap-3">
      <%= button_to "Run", page_check_path(@page), method: :post, class: "border border-gray-200 rounded shadow px-2 py-1 hover:bg-gray-100"  %>
      <%= link_to "Edit", edit_page_path(@page), class: "border border-gray-200 rounded shadow px-2 py-1 hover:bg-gray-100" %>
    </div>
</div>

<%= link_to @page.url, @page.url, class: "text-gray-500", target: :_blank %>

<div class="mt-4">
  <h4 class="font-medium text-gray-700 font-bold">Recent results</h4>
  <%= render @page.results.order(created_at: :desc) %>
</div>

app/views/results/_result.html.erb
<%= tag.div id: dom_id(result), class: "p-1 flex items-center gap-4 w-6/7" do %>
  <div class="w-32 flex gap-1 items-center font-medium">
    <% if result.success %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 text-green-600">
        <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
      </svg>
      Success
    <% else %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 text-gray-400">
        <path stroke-linecap="round" stroke-linejoin="round" d="m9.75 9.75 4.5 4.5m0-4.5-4.5 4.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
      </svg>
      Fail
    <% end %>
  </div>
  <div class="text-sm text-gray-700 w-20"><%= time_ago_in_words(result.created_at).upcase_first %> ago</div>
<% end %>